#AndroidCS: enforce UTF-8 & locale for Gradle daemon
#Mon Sep 07 13:47:30 GMT 2026
org.gradle.daemon.idletimeout=10800000
systemProp.user.language=en
systemProp.user.country=US
systemProp.sun.jnu.encoding=UTF-8
systemProp.file.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding\=UTF-8 -Dsun.jnu.encoding\=UTF-8 -Duser.language\=en -Duser.country\=US
android.useAndroidX=true
android.enableJetifier=true
