package com.zeroaccess;
import android.content.Context;import android.content.Intent;import android.net.Uri;import android.os.Bundle;import android.provider.Settings;import android.view.*;import android.widget.*;
import androidx.appcompat.app.AppCompatActivity;
public class AppDetailActivity extends AppCompatActivity {
    public static final String EXTRA_PKG="pkg",EXTRA_NAME="name";
    public static Intent intentFor(Context ctx,AppInfo app){Intent i=new Intent(ctx,AppDetailActivity.class);i.putExtra(EXTRA_PKG,app.packageName);i.putExtra(EXTRA_NAME,app.appName);return i;}
    @Override protected void onCreate(Bundle s){super.onCreate(s);setContentView(R.layout.activity_app_detail);
        String pkg=getIntent().getStringExtra(EXTRA_PKG),name=getIntent().getStringExtra(EXTRA_NAME);if(pkg==null||pkg.isEmpty()){finish();return;}
        ImageView ivBack=findViewById(R.id.iv_back);TextView tvTitle=findViewById(R.id.tv_toolbar_title);ImageView ivIcon=findViewById(R.id.iv_app_icon);TextView tvName=findViewById(R.id.tv_app_name),tvPkg=findViewById(R.id.tv_app_package);LinearLayout llP=findViewById(R.id.ll_permissions);View btnM=findViewById(R.id.btn_manage);
        ivBack.setOnClickListener(v->finish());tvTitle.setText(name!=null?name:pkg);tvName.setText(name!=null?name:pkg);tvPkg.setText(pkg);
        try{ivIcon.setImageDrawable(getPackageManager().getApplicationIcon(pkg));}catch(Exception e){ivIcon.setImageDrawable(getPackageManager().getDefaultActivityIcon());}
        Context appCtx=getApplicationContext();final String fP=pkg;
        new Thread(()->{try{AppInfo found=null;for(AppInfo a:PermissionHelper.getInstalledApps(appCtx))if(a.packageName.equals(fP)){found=a;break;}final AppInfo app=found;runOnUiThread(()->{if(isFinishing()||isDestroyed())return;if(app==null){row(llP,R.drawable.ic_info,0xFF5B8DEF,"Could not load","",false);return;}if(app.hasCamera)row(llP,R.drawable.ic_camera,0xFF5B8DEF,"Camera","Declared in manifest",true);if(app.hasMic)row(llP,R.drawable.ic_microphone,0xFF8B5CF6,"Microphone","Declared in manifest",true);if(app.hasLocation)row(llP,R.drawable.ic_location,0xFFE8A440,"Location","Declared in manifest",true);if(app.hasStorage)row(llP,R.drawable.ic_storage,0xFF22C4D0,"Storage","Declared in manifest",true);if(app.hasContacts)row(llP,R.drawable.ic_contacts,0xFF22C55E,"Contacts","Declared in manifest",true);if(llP.getChildCount()==0)row(llP,R.drawable.ic_verified,0xFF22C55E,"No sensitive permissions","Safe",false);});}catch(Exception e){e.printStackTrace();}}).start();
        btnM.setOnClickListener(v->{try{Intent i=new Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS);i.setData(Uri.fromParts("package",fP,null));startActivity(i);}catch(Exception e){e.printStackTrace();}});}
    private void row(LinearLayout c,int iconRes,int iconColor,String label,String detail,boolean risky){try{View row=LayoutInflater.from(this).inflate(R.layout.item_permission_row,c,false);ImageView iv=row.findViewById(R.id.iv_perm_icon);iv.setImageResource(iconRes);iv.setColorFilter(iconColor);((TextView)row.findViewById(R.id.tv_perm_name)).setText(label);((TextView)row.findViewById(R.id.tv_perm_detail)).setText(detail);TextView st=row.findViewById(R.id.tv_perm_status);if(risky){st.setText("Allowed");st.setTextColor(0xFFE05A5A);st.setBackgroundResource(R.drawable.bg_tag_red);}else{st.setText("Safe");st.setTextColor(0xFF22C55E);st.setBackgroundResource(R.drawable.bg_tag_green);}c.addView(row);}catch(Exception e){e.printStackTrace();}}
}